### ISSUE TITLE
Enable integration test in CI

### ISSUE THREAD

**Issue by mossmaurice** [eclipse-iceoryx/iceoryx-automotive-soa#5]
## Brief feature description

An integration test is already available a `test/test_automotive_soa_binding.py`

## Detailed information

* [ ] Enable the integration test in CI

It might work with the following using the script from the iceoryx repo:

```
  run-integration-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: foxy
      - uses: actions/checkout@v3
      - run: ./build/_deps/tools/ci/run-integration-test.sh
```
